name: Debug Dispatch

on: [repository_dispatch]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "ACTION=${{ github.event.action }}"
          echo "EVENT:"
          echo '${{ toJson(github.event) }}'
